/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/patients`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ImageClick`; params?: Router.UnknownInputParams; } | { pathname: `/components/Modal`; params?: Router.UnknownInputParams; } | { pathname: `/components/PatientDiagnostics`; params?: Router.UnknownInputParams; } | { pathname: `/components/PatientInfos`; params?: Router.UnknownInputParams; } | { pathname: `/components/PatientListItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/Separator`; params?: Router.UnknownInputParams; } | { pathname: `/constants/evolution`; params?: Router.UnknownInputParams; } | { pathname: `/constants/risk`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/i18n`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PatientFile`; params?: Router.UnknownInputParams; } | { pathname: `/store/types`; params?: Router.UnknownInputParams; } | { pathname: `/store/useAppStore`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/patients`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ImageClick`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Modal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PatientDiagnostics`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PatientInfos`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PatientListItem`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Separator`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/evolution`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/risk`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/i18n`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/PatientFile`; params?: Router.UnknownOutputParams; } | { pathname: `/store/types`; params?: Router.UnknownOutputParams; } | { pathname: `/store/useAppStore`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/patients${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/ImageClick${`?${string}` | `#${string}` | ''}` | `/components/Modal${`?${string}` | `#${string}` | ''}` | `/components/PatientDiagnostics${`?${string}` | `#${string}` | ''}` | `/components/PatientInfos${`?${string}` | `#${string}` | ''}` | `/components/PatientListItem${`?${string}` | `#${string}` | ''}` | `/components/Separator${`?${string}` | `#${string}` | ''}` | `/constants/evolution${`?${string}` | `#${string}` | ''}` | `/constants/risk${`?${string}` | `#${string}` | ''}` | `/constants/theme${`?${string}` | `#${string}` | ''}` | `/i18n${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/screens/Home${`?${string}` | `#${string}` | ''}` | `/screens/PatientFile${`?${string}` | `#${string}` | ''}` | `/store/types${`?${string}` | `#${string}` | ''}` | `/store/useAppStore${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/patients`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ImageClick`; params?: Router.UnknownInputParams; } | { pathname: `/components/Modal`; params?: Router.UnknownInputParams; } | { pathname: `/components/PatientDiagnostics`; params?: Router.UnknownInputParams; } | { pathname: `/components/PatientInfos`; params?: Router.UnknownInputParams; } | { pathname: `/components/PatientListItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/Separator`; params?: Router.UnknownInputParams; } | { pathname: `/constants/evolution`; params?: Router.UnknownInputParams; } | { pathname: `/constants/risk`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/i18n`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PatientFile`; params?: Router.UnknownInputParams; } | { pathname: `/store/types`; params?: Router.UnknownInputParams; } | { pathname: `/store/useAppStore`; params?: Router.UnknownInputParams; };
    }
  }
}
